# Generated by Django 6.0.5 on 2026-05-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_student_user_alter_teacher_specialization_and_more'),
        ('certificates', '0001_initial'),
        ('courses', '0002_course_duration_hours_course_has_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('student', 'course')},
        ),
    ]
