# Generated by Django 6.0.5 on 2026-05-29 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_student_user_alter_teacher_specialization_and_more'),
        ('assignments', '0002_assignment_max_score_submission_text_answer_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('assignment', 'student')},
        ),
    ]
