# Generated by Django 6.0.5 on 2026-05-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_final_exam',
            field=models.BooleanField(default=False),
        ),
    ]
